In [1]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from pathlib import Path

In [2]:
import time
from pathlib import Path

import soundfile as sf
import torch
from tqdm import tqdm
from torch import multiprocessing

import sys

In [3]:
stored_files = list(Path('../../Documents/mila-human-wav-txt').glob('*.WAV'))
stored_files

[PosixPath('../../Documents/mila-human-wav-txt/20220826_070000.WAV'),
 PosixPath('../../Documents/mila-human-wav-txt/20220727_083000.WAV'),
 PosixPath('../../Documents/mila-human-wav-txt/20220829_090000.WAV'),
 PosixPath('../../Documents/mila-human-wav-txt/20220730_053000.WAV')]

In [4]:
import batdetect2.api as api

Used `python3 -m pip install batdetect2`

`Successfully installed batdetect2-1.1.1 click-8.1.8 filelock-3.16.1 librosa-0.10.2.post1 matplotlib-3.9.4 mpmath-1.3.0 numpy-1.24.4 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.20.5 nvidia-nvjitlink-cu12-12.6.85 nvidia-nvtx-cu12-12.1.105 pandas-2.2.3 scikit-learn-1.6.0 scipy-1.13.1 soxr-0.5.0.post1 sympy-1.13.3 torch-2.4.1 torchaudio-2.4.1 torchvision-0.19.1 triton-3.0.0 typing-extensions-4.12.2`

In [5]:
from batdetect2.detector.parameters import (
    DEFAULT_MODEL_PATH,
    DEFAULT_PROCESSING_CONFIGURATIONS,
    DEFAULT_SPECTROGRAM_PARAMETERS,
    TARGET_SAMPLERATE_HZ,
)

In [6]:
TARGET_SAMPLERATE_HZ

256000

In [7]:
DEFAULT_SPECTROGRAM_PARAMETERS

{'fft_win_length': 0.002,
 'fft_overlap': 0.75,
 'spec_height': 256,
 'resize_factor': 0.5,
 'spec_divide_factor': 32,
 'max_freq': 120000,
 'min_freq': 10000,
 'spec_scale': 'pcen',
 'denoise_spec_avg': True,
 'max_scale_spec': False}

In [8]:
DEFAULT_PROCESSING_CONFIGURATIONS

{'detection_threshold': 0.01,
 'spec_slices': False,
 'chunk_size': 3,
 'spec_features': False,
 'cnn_features': False,
 'quiet': True,
 'target_samp_rate': 256000,
 'fft_win_length': 0.002,
 'fft_overlap': 0.75,
 'resize_factor': 0.5,
 'spec_divide_factor': 32,
 'spec_height': 256,
 'scale_raw_audio': False,
 'class_names': [],
 'time_expansion': 1,
 'top_n': 3,
 'return_raw_preds': False,
 'max_duration': None,
 'nms_kernel_size': 9,
 'max_freq': 120000,
 'min_freq': 10000,
 'nms_top_k_per_sec': 200,
 'spec_scale': 'pcen',
 'denoise_spec_avg': True,
 'max_scale_spec': False}

In [9]:
# Use GPU if available
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# Default model
MODEL, PARAMS = api.load_model(DEFAULT_MODEL_PATH, device=DEVICE)

In [10]:
PARAMS

{'data_dir': '/data1/bat_data/data/',
 'ann_dir': '/data1/bat_data/annotations/anns_same/',
 'train_split': 'same',
 'standardize_classs_names_ip': 'Rhinolophus ferrumequinum;Rhinolophus hipposideros',
 'model_name': 'Net2DFast',
 'num_filters': 128,
 'experiment': '../../experiments/2021_12_13__20_20_37/',
 'model_file_name': '../../experiments/2021_12_13__20_20_37/2021_12_13__20_20_37.pth.tar',
 'op_im_dir': '../../experiments/2021_12_13__20_20_37/op_ims/',
 'op_im_dir_test': '../../experiments/2021_12_13__20_20_37/op_ims_test/',
 'notes': '',
 'target_samp_rate': 256000,
 'fft_win_length': 0.002,
 'fft_overlap': 0.75,
 'max_freq': 120000,
 'min_freq': 10000,
 'resize_factor': 0.5,
 'spec_height': 256,
 'spec_train_width': 512,
 'spec_divide_factor': 32,
 'denoise_spec_avg': True,
 'scale_raw_audio': False,
 'max_scale_spec': False,
 'spec_scale': 'pcen',
 'detection_overlap': 0.01,
 'ignore_start_end': 0.01,
 'detection_threshold': 0.01,
 'nms_kernel_size': 9,
 'nms_top_k_per_sec': 200,
 'target_sigma': 2.0,
 'aug_prob': 0.2,
 'augment_at_train': True,
 'augment_at_train_combine': True,
 'echo_max_delay': 0.005,
 'stretch_squeeze_delta': 0.04,
 'mask_max_time_perc': 0.05,
 'mask_max_freq_perc': 0.1,
 'spec_amp_scaling': 2.0,
 'aug_sampling_rates': [220500,
  256000,
  300000,
  312500,
  384000,
  441000,
  500000],
 'train_loss': 'focal',
 'det_loss_weight': 1.0,
 'size_loss_weight': 0.1,
 'class_loss_weight': 2.0,
 'individual_loss_weight': 0.0,
 'emb_dim': 0,
 'lr': 0.001,
 'batch_size': 8,
 'num_workers': 4,
 'num_epochs': 200,
 'num_eval_epochs': 5,
 'device': 'cuda',
 'save_test_image_during_train': False,
 'save_test_image_after_train': True,
 'convert_to_genus': False,
 'genus_mapping': [0, 1, 2, 2, 2, 2, 2, 2, 3, 3, 4, 4, 4, 5, 5, 6, 6],
 'class_names': ['Barbastellus barbastellus',
  'Eptesicus serotinus',
  'Myotis alcathoe',
  'Myotis bechsteinii',
  'Myotis brandtii',
  'Myotis daubentonii',
  'Myotis mystacinus',
  'Myotis nattereri',
  'Nyctalus leisleri',
  'Nyctalus noctula',
  'Pipistrellus nathusii',
  'Pipistrellus pipistrellus',
  'Pipistrellus pygmaeus',
  'Plecotus auritus',
  'Plecotus austriacus',
  'Rhinolophus ferrumequinum',
  'Rhinolophus hipposideros'],
 'classes_to_ignore': ['', ' ', 'Unknown', 'Not Bat'],
 'generic_class': ['Bat'],
 'events_of_interest': ['Echolocation'],
 'standardize_classs_names': ['Rhinolophus ferrumequinum',
  'Rhinolophus hipposideros'],
 'train_sets': [{'dataset_name': 'BatDetective',
   'is_test': False,
   'is_binary': True,
   'ann_path': 'train_set_bulgaria_batdetective_with_bbs.json',
   'wav_path': 'bat_detective/audio/'},
  {'dataset_name': 'bat_logger_qeop_empty',
   'is_test': False,
   'is_binary': True,
   'ann_path': 'bat_logger_qeop_empty.json',
   'wav_path': 'bat_logger_qeop_empty/audio/'},
  {'dataset_name': 'bat_logger_2016_empty',
   'is_test': False,
   'is_binary': True,
   'ann_path': 'train_set_bat_logger_2016_empty.json',
   'wav_path': 'bat_logger_2016/audio/'},
  {'dataset_name': 'echobank',
   'is_test': False,
   'is_binary': False,
   'ann_path': 'Echobank_train_expert_TRAIN.json',
   'wav_path': 'echobank/audio/'},
  {'dataset_name': 'sn_scot_nor',
   'is_test': False,
   'is_binary': False,
   'ann_path': 'sn_scot_nor_0.5_expert_TRAIN.json',
   'wav_path': 'sn_scot_nor/audio/'},
  {'dataset_name': 'BCT_1_sec',
   'is_test': False,
   'is_binary': False,
   'ann_path': 'BCT_1_sec_train_expert_TRAIN.json',
   'wav_path': 'BCT_1_sec/audio/'},
  {'dataset_name': 'bcireland',
   'is_test': False,
   'is_binary': False,
   'ann_path': 'bcireland_expert_TRAIN.json',
   'wav_path': 'bcireland/audio/'},
  {'dataset_name': 'rhinolophus_steve_BCT',
   'is_test': False,
   'is_binary': False,
   'ann_path': 'rhinolophus_steve_BCT_expert_TRAIN.json',
   'wav_path': 'rhinolophus_steve_BCT/audio/'},
  {'dataset_name': 'bat_data_martyn_2018',
   'is_test': False,
   'is_binary': False,
   'ann_path': 'BritishBatCalls_MartynCooke_2018_1_sec_train_expert_TRAIN.json',
   'wav_path': 'bat_data_martyn_2018/audio/'},
  {'dataset_name': 'bat_data_martyn_2018_test',
   'is_test': False,
   'is_binary': False,
   'ann_path': 'BritishBatCalls_MartynCooke_2018_1_sec_test_expert_TRAIN.json',
   'wav_path': 'bat_data_martyn_2018_test/audio/'},
  {'dataset_name': 'bat_data_martyn_2019',
   'is_test': False,
   'is_binary': False,
   'ann_path': 'BritishBatCalls_MartynCooke_2019_1_sec_train_expert_TRAIN.json',
   'wav_path': 'bat_data_martyn_2019/audio/'},
  {'dataset_name': 'bat_data_martyn_2019_test',
   'is_test': False,
   'is_binary': False,
   'ann_path': 'BritishBatCalls_MartynCooke_2019_1_sec_test_expert_TRAIN.json',
   'wav_path': 'bat_data_martyn_2019_test/audio/'}],
 'test_sets': [{'dataset_name': 'echobank',
   'is_test': True,
   'is_binary': False,
   'ann_path': 'Echobank_train_expert_TEST.json',
   'wav_path': 'echobank/audio/'},
  {'dataset_name': 'sn_scot_nor',
   'is_test': True,
   'is_binary': False,
   'ann_path': 'sn_scot_nor_0.5_expert_TEST.json',
   'wav_path': 'sn_scot_nor/audio/'},
  {'dataset_name': 'BCT_1_sec',
   'is_test': True,
   'is_binary': False,
   'ann_path': 'BCT_1_sec_train_expert_TEST.json',
   'wav_path': 'BCT_1_sec/audio/'},
  {'dataset_name': 'bcireland',
   'is_test': True,
   'is_binary': False,
   'ann_path': 'bcireland_expert_TEST.json',
   'wav_path': 'bcireland/audio/'},
  {'dataset_name': 'rhinolophus_steve_BCT',
   'is_test': True,
   'is_binary': False,
   'ann_path': 'rhinolophus_steve_BCT_expert_TEST.json',
   'wav_path': 'rhinolophus_steve_BCT/audio/'},
  {'dataset_name': 'bat_data_martyn_2018',
   'is_test': True,
   'is_binary': False,
   'ann_path': 'BritishBatCalls_MartynCooke_2018_1_sec_train_expert_TEST.json',
   'wav_path': 'bat_data_martyn_2018/audio/'},
  {'dataset_name': 'bat_data_martyn_2018_test',
   'is_test': True,
   'is_binary': False,
   'ann_path': 'BritishBatCalls_MartynCooke_2018_1_sec_test_expert_TEST.json',
   'wav_path': 'bat_data_martyn_2018_test/audio/'},
  {'dataset_name': 'bat_data_martyn_2019',
   'is_test': True,
   'is_binary': False,
   'ann_path': 'BritishBatCalls_MartynCooke_2019_1_sec_train_expert_TEST.json',
   'wav_path': 'bat_data_martyn_2019/audio/'},
  {'dataset_name': 'bat_data_martyn_2019_test',
   'is_test': True,
   'is_binary': False,
   'ann_path': 'BritishBatCalls_MartynCooke_2019_1_sec_test_expert_TEST.json',
   'wav_path': 'bat_data_martyn_2019_test/audio/'}],
 'class_inv_freq': [1.9637118577957153,
  0.7146786451339722,
  2.441218852996826,
  2.6182825565338135,
  0.955857515335083,
  0.29615065455436707,
  0.6982086896896362,
  0.7116808295249939,
  1.6066733598709106,
  5.473054885864258,
  1.386149525642395,
  1.0264047384262085,
  0.7815048694610596,
  1.8502148389816284,
  2.458908796310425,
  0.885977566242218,
  0.8449437618255615],
 'genus_names': ['Barbastellus',
  'Eptesicus',
  'Myotis',
  'Nyctalus',
  'Pipistrellus',
  'Plecotus',
  'Rhinolophus'],
 'class_names_short': ['Bar bar',
  'Ept ser',
  'Myo alc',
  'Myo bec',
  'Myo bra',
  'Myo dau',
  'Myo mys',
  'Myo nat',
  'Nyc lei',
  'Nyc noc',
  'Pip nat',
  'Pip pip',
  'Pip pyg',
  'Ple aur',
  'Ple aus',
  'Rhi fer',
  'Rhi hip'],
 'ip_height': 128}

In [ ]:
# Default processing configuration
ubna_config = api.get_config(detection_threshold=self.detection_threshold,
                                spec_slices = self.spec_slices,
                                chunk_size = self.chunk_size,
                                time_expansion_factor = self.time_expansion_factor
                                quiet = self.quiet,
                                cnn_features = self.cnn_features)

In [12]:
# Default processing configuration
ubna_config = api.get_config(detection_threshold=0.5)

In [16]:
'alpha' in ubna_config.keys()

False

In [12]:
pd.DataFrame([ubna_config]).iloc[:,:10]

,detection_threshold,spec_slices,chunk_size,spec_features,cnn_features,quiet,target_samp_rate,fft_win_length,fft_overlap,resize_factor
0,0.5,False,3,False,False,True,256000,0.002,0.75,0.5

In [13]:
pd.DataFrame([ubna_config]).iloc[:,10:20]

,spec_divide_factor,spec_height,scale_raw_audio,class_names,time_expansion,top_n,return_raw_preds,max_duration,nms_kernel_size,max_freq
0,32,256,False,"[Barbastellus barbastellus, Eptesicus serotinu...",1,3,False,None,9,120000

In [14]:
pd.DataFrame([ubna_config]).iloc[:,20:30]

,min_freq,nms_top_k_per_sec,spec_scale,denoise_spec_avg,max_scale_spec,data_dir,ann_dir,train_split,standardize_classs_names_ip,model_name
0,10000,200,pcen,True,False,/data1/bat_data/data/,/data1/bat_data/annotations/anns_same/,same,Rhinolophus ferrumequinum;Rhinolophus hipposid...,Net2DFast

In [15]:
pd.DataFrame([ubna_config]).iloc[:,30:40]

,num_filters,experiment,model_file_name,op_im_dir,op_im_dir_test,notes,spec_train_width,detection_overlap,ignore_start_end,target_sigma
0,128,../../experiments/2021_12_13__20_20_37/,../../experiments/2021_12_13__20_20_37/2021_12...,../../experiments/2021_12_13__20_20_37/op_ims/,../../experiments/2021_12_13__20_20_37/op_ims_...,,512,0.01,0.01,2.0

In [16]:
pd.DataFrame([ubna_config]).iloc[:,40:50]

,aug_prob,augment_at_train,augment_at_train_combine,echo_max_delay,stretch_squeeze_delta,mask_max_time_perc,mask_max_freq_perc,spec_amp_scaling,aug_sampling_rates,train_loss
0,0.2,True,True,0.005,0.04,0.05,0.1,2.0,"[220500, 256000, 300000, 312500, 384000, 44100...",focal

In [17]:
pd.DataFrame([ubna_config]).iloc[:,50:60]

,det_loss_weight,size_loss_weight,class_loss_weight,individual_loss_weight,emb_dim,lr,batch_size,num_workers,num_epochs,num_eval_epochs
0,1.0,0.1,2.0,0.0,0,0.001,8,4,200,5

In [18]:
# Process audio file
results = api.process_file(stored_files[0], config=ubna_config)

KeyboardInterrupt:

In [75]:
results['pred_dict']['annotation']

[{'start_time': 0.0015,
  'end_time': 0.0328,
  'low_freq': 68437,
  'high_freq': 79512,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.028,
  'det_prob': 0.028,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.0015,
  'end_time': 0.0098,
  'low_freq': 47812,
  'high_freq': 51963,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.029,
  'det_prob': 0.035,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.0015,
  'end_time': 0.0096,
  'low_freq': 22890,
  'high_freq': 29195,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.011,
  'det_prob': 0.033,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.0685,
  'end_time': 0.0826,
  'low_freq': 22890,
  'high_freq': 27036,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.014,
  'det_prob': 0.025,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.0725,
  'end_time': 0.0786,
  'low_freq': 11718,
  'high_freq': 64612,
  'class': 'Myotis nattereri',
  'class_prob': 0.01,
  'det_prob': 0.025,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.0805,
  'end_time': 0.1214,
  'low_freq': 68437,
  'high_freq': 83024,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.027,
  'det_prob': 0.027,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.1225,
  'end_time': 0.1318,
  'low_freq': 25468,
  'high_freq': 33915,
  'class': 'Eptesicus serotinus',
  'class_prob': 0.01,
  'det_prob': 0.025,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.2355,
  'end_time': 0.2745,
  'low_freq': 68437,
  'high_freq': 81543,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.025,
  'det_prob': 0.025,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.2855,
  'end_time': 0.2953,
  'low_freq': 21171,
  'high_freq': 26132,
  'class': 'Plecotus austriacus',
  'class_prob': 0.009,
  'det_prob': 0.026,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.2875,
  'end_time': 0.3263,
  'low_freq': 68437,
  'high_freq': 82744,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.024,
  'det_prob': 0.024,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.3305,
  'end_time': 0.3414,
  'low_freq': 22890,
  'high_freq': 27508,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.012,
  'det_prob': 0.023,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.3455,
  'end_time': 0.388,
  'low_freq': 68437,
  'high_freq': 82760,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.023,
  'det_prob': 0.023,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.3655,
  'end_time': 0.3761,
  'low_freq': 23750,
  'high_freq': 29273,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.011,
  'det_prob': 0.024,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.4005,
  'end_time': 0.4068,
  'low_freq': 17734,
  'high_freq': 29245,
  'class': 'Plecotus austriacus',
  'class_prob': 0.069,
  'det_prob': 0.093,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.5175,
  'end_time': 0.5286,
  'low_freq': 23750,
  'high_freq': 28650,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.011,
  'det_prob': 0.023,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.5275,
  'end_time': 0.5678,
  'low_freq': 68437,
  'high_freq': 82236,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.022,
  'det_prob': 0.022,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.5385,
  'end_time': 0.5792,
  'low_freq': 68437,
  'high_freq': 82987,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.023,
  'det_prob': 0.023,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.5495,
  'end_time': 0.5579,
  'low_freq': 27187,
  'high_freq': 38071,
  'class': 'Eptesicus serotinus',
  'class_prob': 0.009,
  'det_prob': 0.025,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.5585,
  'end_time': 0.5935,
  'low_freq': 68437,
  'high_freq': 81357,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.025,
  'det_prob': 0.025,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.5595,
  'end_time': 0.5708,
  'low_freq': 28906,
  'high_freq': 35693,
  'class': 'Eptesicus serotinus',
  'class_prob': 0.011,
  'det_prob': 0.024,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.6425,
  'end_time': 0.6502,
  'low_freq': 28906,
  'high_freq': 40312,
  'class': 'Eptesicus serotinus',
  'class_prob': 0.007,
  'det_prob': 0.024,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.6475,
  'end_time': 0.6571,
  'low_freq': 24609,
  'high_freq': 30552,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.01,
  'det_prob': 0.024,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.6755,
  'end_time': 0.715,
  'low_freq': 68437,
  'high_freq': 82421,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.028,
  'det_prob': 0.028,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.7015,
  'end_time': 0.71,
  'low_freq': 43515,
  'high_freq': 50527,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.033,
  'det_prob': 0.04,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.7055,
  'end_time': 0.7122,
  'low_freq': 27187,
  'high_freq': 41333,
  'class': 'Eptesicus serotinus',
  'class_prob': 0.006,
  'det_prob': 0.024,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.7345,
  'end_time': 0.7468,
  'low_freq': 14296,
  'high_freq': 21548,
  'class': 'Nyctalus noctula',
  'class_prob': 0.015,
  'det_prob': 0.023,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.7395,
  'end_time': 0.7472,
  'low_freq': 28906,
  'high_freq': 41113,
  'class': 'Eptesicus serotinus',
  'class_prob': 0.009,
  'det_prob': 0.029,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.7675,
  'end_time': 0.7788,
  'low_freq': 22890,
  'high_freq': 27291,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.012,
  'det_prob': 0.023,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.8125,
  'end_time': 0.8488,
  'low_freq': 68437,
  'high_freq': 81494,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.022,
  'det_prob': 0.022,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.8135,
  'end_time': 0.822,
  'low_freq': 26328,
  'high_freq': 39741,
  'class': 'Eptesicus serotinus',
  'class_prob': 0.008,
  'det_prob': 0.022,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.8795,
  'end_time': 0.8887,
  'low_freq': 25468,
  'high_freq': 35105,
  'class': 'Eptesicus serotinus',
  'class_prob': 0.008,
  'det_prob': 0.023,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.8805,
  'end_time': 0.9228,
  'low_freq': 68437,
  'high_freq': 82818,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.031,
  'det_prob': 0.031,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.9005,
  'end_time': 0.9134,
  'low_freq': 17734,
  'high_freq': 24500,
  'class': 'Nyctalus noctula',
  'class_prob': 0.03,
  'det_prob': 0.046,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.9185,
  'end_time': 0.9546,
  'low_freq': 68437,
  'high_freq': 81455,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.025,
  'det_prob': 0.025,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.9265,
  'end_time': 0.9648,
  'low_freq': 68437,
  'high_freq': 81406,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.023,
  'det_prob': 0.023,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.9295,
  'end_time': 0.938,
  'low_freq': 50390,
  'high_freq': 56121,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.02,
  'det_prob': 0.023,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.9625,
  'end_time': 0.9724,
  'low_freq': 28046,
  'high_freq': 35773,
  'class': 'Eptesicus serotinus',
  'class_prob': 0.011,
  'det_prob': 0.022,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 0.9845,
  'end_time': 0.9955,
  'low_freq': 24609,
  'high_freq': 30096,
  'class': 'Eptesicus serotinus',
  'class_prob': 0.03,
  'det_prob': 0.081,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.0425,
  'end_time': 1.0496,
  'low_freq': 14296,
  'high_freq': 25832,
  'class': 'Plecotus auritus',
  'class_prob': 0.017,
  'det_prob': 0.026,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.0535,
  'end_time': 1.0632,
  'low_freq': 27187,
  'high_freq': 36094,
  'class': 'Eptesicus serotinus',
  'class_prob': 0.02,
  'det_prob': 0.035,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.0675,
  'end_time': 1.0768,
  'low_freq': 28906,
  'high_freq': 36952,
  'class': 'Eptesicus serotinus',
  'class_prob': 0.009,
  'det_prob': 0.022,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.0875,
  'end_time': 1.0991,
  'low_freq': 22031,
  'high_freq': 26272,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.013,
  'det_prob': 0.024,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.1235,
  'end_time': 1.1358,
  'low_freq': 18593,
  'high_freq': 24078,
  'class': 'Nyctalus noctula',
  'class_prob': 0.011,
  'det_prob': 0.026,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.1325,
  'end_time': 1.1444,
  'low_freq': 21171,
  'high_freq': 25405,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.013,
  'det_prob': 0.022,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.1475,
  'end_time': 1.1851,
  'low_freq': 68437,
  'high_freq': 82243,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.023,
  'det_prob': 0.023,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.1715,
  'end_time': 1.1824,
  'low_freq': 48671,
  'high_freq': 53003,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.019,
  'det_prob': 0.022,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.1905,
  'end_time': 1.2015,
  'low_freq': 23750,
  'high_freq': 28741,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.011,
  'det_prob': 0.022,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.2325,
  'end_time': 1.2411,
  'low_freq': 48671,
  'high_freq': 55793,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.019,
  'det_prob': 0.022,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.2965,
  'end_time': 1.307,
  'low_freq': 21171,
  'high_freq': 25940,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.01,
  'det_prob': 0.023,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.3195,
  'end_time': 1.3317,
  'low_freq': 25468,
  'high_freq': 31892,
  'class': 'Eptesicus serotinus',
  'class_prob': 0.012,
  'det_prob': 0.027,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.3285,
  'end_time': 1.3672,
  'low_freq': 68437,
  'high_freq': 82520,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.024,
  'det_prob': 0.024,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.3425,
  'end_time': 1.3487,
  'low_freq': 14296,
  'high_freq': 29730,
  'class': 'Plecotus auritus',
  'class_prob': 0.045,
  'det_prob': 0.056,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.3575,
  'end_time': 1.3682,
  'low_freq': 22031,
  'high_freq': 26987,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.01,
  'det_prob': 0.022,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.3785,
  'end_time': 1.3885,
  'low_freq': 50390,
  'high_freq': 55217,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.047,
  'det_prob': 0.05,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.4125,
  'end_time': 1.4522,
  'low_freq': 68437,
  'high_freq': 82487,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.041,
  'det_prob': 0.041,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.4575,
  'end_time': 1.4963,
  'low_freq': 68437,
  'high_freq': 82625,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.023,
  'det_prob': 0.023,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.4745,
  'end_time': 1.5142,
  'low_freq': 68437,
  'high_freq': 82713,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.023,
  'det_prob': 0.023,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.5085,
  'end_time': 1.55,
  'low_freq': 68437,
  'high_freq': 83539,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.029,
  'det_prob': 0.029,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.5215,
  'end_time': 1.5637,
  'low_freq': 68437,
  'high_freq': 82357,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.026,
  'det_prob': 0.026,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.5275,
  'end_time': 1.5682,
  'low_freq': 68437,
  'high_freq': 82888,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.026,
  'det_prob': 0.026,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.5345,
  'end_time': 1.5445,
  'low_freq': 28906,
  'high_freq': 37236,
  'class': 'Eptesicus serotinus',
  'class_prob': 0.011,
  'det_prob': 0.028,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.5615,
  'end_time': 1.5721,
  'low_freq': 23750,
  'high_freq': 28908,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.014,
  'det_prob': 0.029,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.5775,
  'end_time': 1.587,
  'low_freq': 25468,
  'high_freq': 33176,
  'class': 'Eptesicus serotinus',
  'class_prob': 0.01,
  'det_prob': 0.023,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.5955,
  'end_time': 1.6032,
  'low_freq': 27187,
  'high_freq': 40884,
  'class': 'Eptesicus serotinus',
  'class_prob': 0.008,
  'det_prob': 0.023,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.6315,
  'end_time': 1.6682,
  'low_freq': 68437,
  'high_freq': 81348,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.022,
  'det_prob': 0.022,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.6545,
  'end_time': 1.6601,
  'low_freq': 48671,
  'high_freq': 57223,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.02,
  'det_prob': 0.023,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.6675,
  'end_time': 1.675,
  'low_freq': 28046,
  'high_freq': 42728,
  'class': 'Eptesicus serotinus',
  'class_prob': 0.008,
  'det_prob': 0.024,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.7025,
  'end_time': 1.7133,
  'low_freq': 22890,
  'high_freq': 27866,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.011,
  'det_prob': 0.023,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.7135,
  'end_time': 1.721,
  'low_freq': 27187,
  'high_freq': 40147,
  'class': 'Eptesicus serotinus',
  'class_prob': 0.007,
  'det_prob': 0.022,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.7295,
  'end_time': 1.7372,
  'low_freq': 46953,
  'high_freq': 51210,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.37,
  'det_prob': 0.411,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.7605,
  'end_time': 1.8035,
  'low_freq': 68437,
  'high_freq': 83801,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.039,
  'det_prob': 0.039,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.8095,
  'end_time': 1.8213,
  'low_freq': 27187,
  'high_freq': 34047,
  'class': 'Eptesicus serotinus',
  'class_prob': 0.017,
  'det_prob': 0.033,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.8335,
  'end_time': 1.8445,
  'low_freq': 22890,
  'high_freq': 28719,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.01,
  'det_prob': 0.024,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.8435,
  'end_time': 1.8513,
  'low_freq': 23750,
  'high_freq': 32056,
  'class': 'Plecotus austriacus',
  'class_prob': 0.01,
  'det_prob': 0.024,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.8855,
  'end_time': 1.9243,
  'low_freq': 68437,
  'high_freq': 81979,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.023,
  'det_prob': 0.023,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 1.9095,
  'end_time': 1.916,
  'low_freq': 23750,
  'high_freq': 35566,
  'class': 'Plecotus austriacus',
  'class_prob': 0.012,
  'det_prob': 0.028,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 2.0435,
  'end_time': 2.0539,
  'low_freq': 22031,
  'high_freq': 27315,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.01,
  'det_prob': 0.024,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 2.0495,
  'end_time': 2.0876,
  'low_freq': 68437,
  'high_freq': 82284,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.023,
  'det_prob': 0.023,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 2.1145,
  'end_time': 2.1208,
  'low_freq': 28906,
  'high_freq': 44972,
  'class': 'Eptesicus serotinus',
  'class_prob': 0.007,
  'det_prob': 0.028,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 2.1755,
  'end_time': 2.2161,
  'low_freq': 68437,
  'high_freq': 82438,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.038,
  'det_prob': 0.038,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 2.2095,
  'end_time': 2.2177,
  'low_freq': 45234,
  'high_freq': 53538,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.019,
  'det_prob': 0.023,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 2.2135,
  'end_time': 2.2248,
  'low_freq': 22031,
  'high_freq': 27296,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.011,
  'det_prob': 0.024,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 2.2435,
  'end_time': 2.2508,
  'low_freq': 34921,
  'high_freq': 46191,
  'class': 'Myotis daubentonii',
  'class_prob': 0.006,
  'det_prob': 0.022,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 2.2475,
  'end_time': 2.2862,
  'low_freq': 68437,
  'high_freq': 82112,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.022,
  'det_prob': 0.022,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 2.2545,
  'end_time': 2.2925,
  'low_freq': 68437,
  'high_freq': 81887,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.022,
  'det_prob': 0.022,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 2.2715,
  'end_time': 2.2783,
  'low_freq': 15156,
  'high_freq': 26999,
  'class': 'Plecotus auritus',
  'class_prob': 0.039,
  'det_prob': 0.052,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 2.2895,
  'end_time': 2.3004,
  'low_freq': 24609,
  'high_freq': 29780,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.011,
  'det_prob': 0.025,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 2.3105,
  'end_time': 2.3488,
  'low_freq': 68437,
  'high_freq': 82410,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.029,
  'det_prob': 0.029,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 2.3165,
  'end_time': 2.3275,
  'low_freq': 23750,
  'high_freq': 28912,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.012,
  'det_prob': 0.026,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 2.3215,
  'end_time': 2.3336,
  'low_freq': 50390,
  'high_freq': 57118,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.025,
  'det_prob': 0.03,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 2.3535,
  'end_time': 2.3896,
  'low_freq': 68437,
  'high_freq': 81855,
  'class': 'Rhinolophus ferrumequinum',
  'class_prob': 0.023,
  'det_prob': 0.023,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 2.3725,
  'end_time': 2.415,
  'low_freq': 68437,
  'high_freq': 82717,

In [37]:
pd.DataFrame(results['pred_dict']['annotation'])

,start_time,end_time,low_freq,high_freq,class,class_prob,det_prob,individual,event
0,0.0015,0.0328,68437,79512,Rhinolophus ferrumequinum,0.028,0.028,-1,Echolocation
1,0.0015,0.0098,47812,51963,Pipistrellus pipistrellus,0.029,0.035,-1,Echolocation
2,0.0015,0.0096,22890,29195,Nyctalus leisleri,0.011,0.033,-1,Echolocation
3,0.0685,0.0826,22890,27036,Nyctalus leisleri,0.014,0.025,-1,Echolocation
4,0.0725,0.0786,11718,64612,Myotis nattereri,0.010,0.025,-1,Echolocation
...,...,...,...,...,...,...,...,...,...
92869,1794.9456,1794.9827,68437,81974,Rhinolophus ferrumequinum,0.023,0.023,-1,Echolocation
92870,1794.9504,1794.9609,22031,27451,Nyctalus leisleri,0.011,0.031,-1,Echolocation
92871,1794.9855,1794.9958,22890,29719,Nyctalus leisleri,0.009,0.025,-1,Echolocation
92872,1795.0225,1795.0581,68437,80499,Rhinolophus ferrumequinum,0.029,0.029,-1,Echolocation
92873,1795.0245,1795.0348,25468,40476,Eptesicus serotinus,0.018,0.049,-1,Echolocation