In [1]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from pathlib import Path

In [2]:
import time
from pathlib import Path

import soundfile as sf
import torch
from tqdm import tqdm
from torch import multiprocessing

import sys

In [3]:
stored_files = list(Path('../../Documents/mila-human-wav-txt').glob('*.WAV'))
stored_files

[PosixPath('../../Documents/mila-human-wav-txt/20220826_070000.WAV'),
 PosixPath('../../Documents/mila-human-wav-txt/20220727_083000.WAV'),
 PosixPath('../../Documents/mila-human-wav-txt/20220829_090000.WAV'),
 PosixPath('../../Documents/mila-human-wav-txt/20220730_053000.WAV')]

In [5]:
import batdetect2.api as api

Used `python3 -m pip install batdetect2==1.1.1`

Output: `Successfully installed batdetect2-1.1.1`

In [6]:
from batdetect2.detector.parameters import (
    DEFAULT_MODEL_PATH,
    DEFAULT_PROCESSING_CONFIGURATIONS,
    DEFAULT_SPECTROGRAM_PARAMETERS,
    TARGET_SAMPLERATE_HZ,
)

In [7]:
TARGET_SAMPLERATE_HZ

256000

In [8]:
DEFAULT_SPECTROGRAM_PARAMETERS

{'fft_win_length': 0.002,
 'fft_overlap': 0.75,
 'spec_height': 256,
 'resize_factor': 0.5,
 'spec_divide_factor': 32,
 'max_freq': 120000,
 'min_freq': 10000,
 'spec_scale': 'pcen',
 'denoise_spec_avg': True,
 'max_scale_spec': False}

In [9]:
DEFAULT_PROCESSING_CONFIGURATIONS

{'detection_threshold': 0.01,
 'spec_slices': False,
 'chunk_size': 3,
 'spec_features': False,
 'cnn_features': False,
 'quiet': True,
 'target_samp_rate': 256000,
 'fft_win_length': 0.002,
 'fft_overlap': 0.75,
 'resize_factor': 0.5,
 'spec_divide_factor': 32,
 'spec_height': 256,
 'scale_raw_audio': False,
 'class_names': [],
 'time_expansion': 1,
 'top_n': 3,
 'return_raw_preds': False,
 'max_duration': None,
 'nms_kernel_size': 9,
 'max_freq': 120000,
 'min_freq': 10000,
 'nms_top_k_per_sec': 200,
 'spec_scale': 'pcen',
 'denoise_spec_avg': True,
 'max_scale_spec': False}

In [10]:
# Use GPU if available
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# Default model
MODEL, PARAMS = api.load_model(DEFAULT_MODEL_PATH, device=DEVICE)

In [11]:
PARAMS

{'data_dir': '/data1/bat_data/data/',
 'ann_dir': '/data1/bat_data/annotations/anns_same/',
 'train_split': 'same',
 'standardize_classs_names_ip': 'Rhinolophus ferrumequinum;Rhinolophus hipposideros',
 'model_name': 'Net2DFast',
 'num_filters': 128,
 'experiment': '../../experiments/2021_12_13__20_20_37/',
 'model_file_name': '../../experiments/2021_12_13__20_20_37/2021_12_13__20_20_37.pth.tar',
 'op_im_dir': '../../experiments/2021_12_13__20_20_37/op_ims/',
 'op_im_dir_test': '../../experiments/2021_12_13__20_20_37/op_ims_test/',
 'notes': '',
 'target_samp_rate': 256000,
 'fft_win_length': 0.002,
 'fft_overlap': 0.75,
 'max_freq': 120000,
 'min_freq': 10000,
 'resize_factor': 0.5,
 'spec_height': 256,
 'spec_train_width': 512,
 'spec_divide_factor': 32,
 'denoise_spec_avg': True,
 'scale_raw_audio': False,
 'max_scale_spec': False,
 'spec_scale': 'pcen',
 'detection_overlap': 0.01,
 'ignore_start_end': 0.01,
 'detection_threshold': 0.01,
 'nms_kernel_size': 9,
 'nms_top_k_per_sec': 200,
 'target_sigma': 2.0,
 'aug_prob': 0.2,
 'augment_at_train': True,
 'augment_at_train_combine': True,
 'echo_max_delay': 0.005,
 'stretch_squeeze_delta': 0.04,
 'mask_max_time_perc': 0.05,
 'mask_max_freq_perc': 0.1,
 'spec_amp_scaling': 2.0,
 'aug_sampling_rates': [220500,
  256000,
  300000,
  312500,
  384000,
  441000,
  500000],
 'train_loss': 'focal',
 'det_loss_weight': 1.0,
 'size_loss_weight': 0.1,
 'class_loss_weight': 2.0,
 'individual_loss_weight': 0.0,
 'emb_dim': 0,
 'lr': 0.001,
 'batch_size': 8,
 'num_workers': 4,
 'num_epochs': 200,
 'num_eval_epochs': 5,
 'device': 'cuda',
 'save_test_image_during_train': False,
 'save_test_image_after_train': True,
 'convert_to_genus': False,
 'genus_mapping': [0, 1, 2, 2, 2, 2, 2, 2, 3, 3, 4, 4, 4, 5, 5, 6, 6],
 'class_names': ['Barbastellus barbastellus',
  'Eptesicus serotinus',
  'Myotis alcathoe',
  'Myotis bechsteinii',
  'Myotis brandtii',
  'Myotis daubentonii',
  'Myotis mystacinus',
  'Myotis nattereri',
  'Nyctalus leisleri',
  'Nyctalus noctula',
  'Pipistrellus nathusii',
  'Pipistrellus pipistrellus',
  'Pipistrellus pygmaeus',
  'Plecotus auritus',
  'Plecotus austriacus',
  'Rhinolophus ferrumequinum',
  'Rhinolophus hipposideros'],
 'classes_to_ignore': ['', ' ', 'Unknown', 'Not Bat'],
 'generic_class': ['Bat'],
 'events_of_interest': ['Echolocation'],
 'standardize_classs_names': ['Rhinolophus ferrumequinum',
  'Rhinolophus hipposideros'],
 'train_sets': [{'dataset_name': 'BatDetective',
   'is_test': False,
   'is_binary': True,
   'ann_path': 'train_set_bulgaria_batdetective_with_bbs.json',
   'wav_path': 'bat_detective/audio/'},
  {'dataset_name': 'bat_logger_qeop_empty',
   'is_test': False,
   'is_binary': True,
   'ann_path': 'bat_logger_qeop_empty.json',
   'wav_path': 'bat_logger_qeop_empty/audio/'},
  {'dataset_name': 'bat_logger_2016_empty',
   'is_test': False,
   'is_binary': True,
   'ann_path': 'train_set_bat_logger_2016_empty.json',
   'wav_path': 'bat_logger_2016/audio/'},
  {'dataset_name': 'echobank',
   'is_test': False,
   'is_binary': False,
   'ann_path': 'Echobank_train_expert_TRAIN.json',
   'wav_path': 'echobank/audio/'},
  {'dataset_name': 'sn_scot_nor',
   'is_test': False,
   'is_binary': False,
   'ann_path': 'sn_scot_nor_0.5_expert_TRAIN.json',
   'wav_path': 'sn_scot_nor/audio/'},
  {'dataset_name': 'BCT_1_sec',
   'is_test': False,
   'is_binary': False,
   'ann_path': 'BCT_1_sec_train_expert_TRAIN.json',
   'wav_path': 'BCT_1_sec/audio/'},
  {'dataset_name': 'bcireland',
   'is_test': False,
   'is_binary': False,
   'ann_path': 'bcireland_expert_TRAIN.json',
   'wav_path': 'bcireland/audio/'},
  {'dataset_name': 'rhinolophus_steve_BCT',
   'is_test': False,
   'is_binary': False,
   'ann_path': 'rhinolophus_steve_BCT_expert_TRAIN.json',
   'wav_path': 'rhinolophus_steve_BCT/audio/'},
  {'dataset_name': 'bat_data_martyn_2018',
   'is_test': False,
   'is_binary': False,
   'ann_path': 'BritishBatCalls_MartynCooke_2018_1_sec_train_expert_TRAIN.json',
   'wav_path': 'bat_data_martyn_2018/audio/'},
  {'dataset_name': 'bat_data_martyn_2018_test',
   'is_test': False,
   'is_binary': False,
   'ann_path': 'BritishBatCalls_MartynCooke_2018_1_sec_test_expert_TRAIN.json',
   'wav_path': 'bat_data_martyn_2018_test/audio/'},
  {'dataset_name': 'bat_data_martyn_2019',
   'is_test': False,
   'is_binary': False,
   'ann_path': 'BritishBatCalls_MartynCooke_2019_1_sec_train_expert_TRAIN.json',
   'wav_path': 'bat_data_martyn_2019/audio/'},
  {'dataset_name': 'bat_data_martyn_2019_test',
   'is_test': False,
   'is_binary': False,
   'ann_path': 'BritishBatCalls_MartynCooke_2019_1_sec_test_expert_TRAIN.json',
   'wav_path': 'bat_data_martyn_2019_test/audio/'}],
 'test_sets': [{'dataset_name': 'echobank',
   'is_test': True,
   'is_binary': False,
   'ann_path': 'Echobank_train_expert_TEST.json',
   'wav_path': 'echobank/audio/'},
  {'dataset_name': 'sn_scot_nor',
   'is_test': True,
   'is_binary': False,
   'ann_path': 'sn_scot_nor_0.5_expert_TEST.json',
   'wav_path': 'sn_scot_nor/audio/'},
  {'dataset_name': 'BCT_1_sec',
   'is_test': True,
   'is_binary': False,
   'ann_path': 'BCT_1_sec_train_expert_TEST.json',
   'wav_path': 'BCT_1_sec/audio/'},
  {'dataset_name': 'bcireland',
   'is_test': True,
   'is_binary': False,
   'ann_path': 'bcireland_expert_TEST.json',
   'wav_path': 'bcireland/audio/'},
  {'dataset_name': 'rhinolophus_steve_BCT',
   'is_test': True,
   'is_binary': False,
   'ann_path': 'rhinolophus_steve_BCT_expert_TEST.json',
   'wav_path': 'rhinolophus_steve_BCT/audio/'},
  {'dataset_name': 'bat_data_martyn_2018',
   'is_test': True,
   'is_binary': False,
   'ann_path': 'BritishBatCalls_MartynCooke_2018_1_sec_train_expert_TEST.json',
   'wav_path': 'bat_data_martyn_2018/audio/'},
  {'dataset_name': 'bat_data_martyn_2018_test',
   'is_test': True,
   'is_binary': False,
   'ann_path': 'BritishBatCalls_MartynCooke_2018_1_sec_test_expert_TEST.json',
   'wav_path': 'bat_data_martyn_2018_test/audio/'},
  {'dataset_name': 'bat_data_martyn_2019',
   'is_test': True,
   'is_binary': False,
   'ann_path': 'BritishBatCalls_MartynCooke_2019_1_sec_train_expert_TEST.json',
   'wav_path': 'bat_data_martyn_2019/audio/'},
  {'dataset_name': 'bat_data_martyn_2019_test',
   'is_test': True,
   'is_binary': False,
   'ann_path': 'BritishBatCalls_MartynCooke_2019_1_sec_test_expert_TEST.json',
   'wav_path': 'bat_data_martyn_2019_test/audio/'}],
 'class_inv_freq': [1.9637118577957153,
  0.7146786451339722,
  2.441218852996826,
  2.6182825565338135,
  0.955857515335083,
  0.29615065455436707,
  0.6982086896896362,
  0.7116808295249939,
  1.6066733598709106,
  5.473054885864258,
  1.386149525642395,
  1.0264047384262085,
  0.7815048694610596,
  1.8502148389816284,
  2.458908796310425,
  0.885977566242218,
  0.8449437618255615],
 'genus_names': ['Barbastellus',
  'Eptesicus',
  'Myotis',
  'Nyctalus',
  'Pipistrellus',
  'Plecotus',
  'Rhinolophus'],
 'class_names_short': ['Bar bar',
  'Ept ser',
  'Myo alc',
  'Myo bec',
  'Myo bra',
  'Myo dau',
  'Myo mys',
  'Myo nat',
  'Nyc lei',
  'Nyc noc',
  'Pip nat',
  'Pip pip',
  'Pip pyg',
  'Ple aur',
  'Ple aus',
  'Rhi fer',
  'Rhi hip'],
 'ip_height': 128}

In [12]:
# Default processing configuration
ubna_config = api.get_config(detection_threshold=0.5)

In [12]:
pd.DataFrame([ubna_config]).iloc[:,:10]

,detection_threshold,spec_slices,chunk_size,spec_features,cnn_features,quiet,target_samp_rate,fft_win_length,fft_overlap,resize_factor
0,0.5,False,3,False,False,True,256000,0.002,0.75,0.5

In [13]:
pd.DataFrame([ubna_config]).iloc[:,10:20]

,spec_divide_factor,spec_height,scale_raw_audio,class_names,time_expansion,top_n,return_raw_preds,max_duration,nms_kernel_size,max_freq
0,32,256,False,"[Barbastellus barbastellus, Eptesicus serotinu...",1,3,False,None,9,120000

In [14]:
pd.DataFrame([ubna_config]).iloc[:,20:30]

,min_freq,nms_top_k_per_sec,spec_scale,denoise_spec_avg,max_scale_spec,data_dir,ann_dir,train_split,standardize_classs_names_ip,model_name
0,10000,200,pcen,True,False,/data1/bat_data/data/,/data1/bat_data/annotations/anns_same/,same,Rhinolophus ferrumequinum;Rhinolophus hipposid...,Net2DFast

In [15]:
pd.DataFrame([ubna_config]).iloc[:,30:40]

,num_filters,experiment,model_file_name,op_im_dir,op_im_dir_test,notes,spec_train_width,detection_overlap,ignore_start_end,target_sigma
0,128,../../experiments/2021_12_13__20_20_37/,../../experiments/2021_12_13__20_20_37/2021_12...,../../experiments/2021_12_13__20_20_37/op_ims/,../../experiments/2021_12_13__20_20_37/op_ims_...,,512,0.01,0.01,2.0

In [16]:
pd.DataFrame([ubna_config]).iloc[:,40:50]

,aug_prob,augment_at_train,augment_at_train_combine,echo_max_delay,stretch_squeeze_delta,mask_max_time_perc,mask_max_freq_perc,spec_amp_scaling,aug_sampling_rates,train_loss
0,0.2,True,True,0.005,0.04,0.05,0.1,2.0,"[220500, 256000, 300000, 312500, 384000, 44100...",focal

In [17]:
pd.DataFrame([ubna_config]).iloc[:,50:60]

,det_loss_weight,size_loss_weight,class_loss_weight,individual_loss_weight,emb_dim,lr,batch_size,num_workers,num_epochs,num_eval_epochs
0,1.0,0.1,2.0,0.0,0,0.001,8,4,200,5

In [18]:
# Process audio file
results = api.process_file(stored_files[0], config=ubna_config)

In [19]:
results['pred_dict']['annotation']

[{'start_time': 3.7705,
  'end_time': 3.7774,
  'low_freq': 46093,
  'high_freq': 54897,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.505,
  'det_prob': 0.541,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 4.3085,
  'end_time': 4.3139,
  'low_freq': 46093,
  'high_freq': 58971,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.512,
  'det_prob': 0.542,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 5.0035,
  'end_time': 5.0094,
  'low_freq': 45234,
  'high_freq': 60411,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.491,
  'det_prob': 0.544,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 5.1515,
  'end_time': 5.1568,
  'low_freq': 46093,
  'high_freq': 61553,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.443,
  'det_prob': 0.519,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 5.2725,
  'end_time': 5.2776,
  'low_freq': 46093,
  'high_freq': 61355,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.557,
  'det_prob': 0.627,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 5.7835,
  'end_time': 5.7888,
  'low_freq': 44375,
  'high_freq': 58786,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.628,
  'det_prob': 0.714,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 8.2815,
  'end_time': 8.2895,
  'low_freq': 38359,
  'high_freq': 47027,
  'class': 'Pipistrellus nathusii',
  'class_prob': 0.346,
  'det_prob': 0.513,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 9.1595,
  'end_time': 9.1669,
  'low_freq': 38359,
  'high_freq': 47401,
  'class': 'Pipistrellus nathusii',
  'class_prob': 0.447,
  'det_prob': 0.532,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 9.4335,
  'end_time': 9.4418,
  'low_freq': 38359,
  'high_freq': 45616,
  'class': 'Pipistrellus nathusii',
  'class_prob': 0.454,
  'det_prob': 0.557,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 9.6025,
  'end_time': 9.611,
  'low_freq': 38359,
  'high_freq': 48501,
  'class': 'Pipistrellus nathusii',
  'class_prob': 0.406,
  'det_prob': 0.525,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 10.8665,
  'end_time': 10.8737,
  'low_freq': 38359,
  'high_freq': 47874,
  'class': 'Pipistrellus nathusii',
  'class_prob': 0.502,
  'det_prob': 0.529,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 32.6185,
  'end_time': 32.6344,
  'low_freq': 24609,
  'high_freq': 28318,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.437,
  'det_prob': 0.574,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 36.7825,
  'end_time': 36.7982,
  'low_freq': 24609,
  'high_freq': 29390,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.43,
  'det_prob': 0.527,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 37.3135,
  'end_time': 37.3277,
  'low_freq': 23750,
  'high_freq': 28035,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.355,
  'det_prob': 0.519,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 37.9195,
  'end_time': 37.9353,
  'low_freq': 24609,
  'high_freq': 28338,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.366,
  'det_prob': 0.561,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 38.6305,
  'end_time': 38.6472,
  'low_freq': 23750,
  'high_freq': 29324,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.377,
  'det_prob': 0.594,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 38.9305,
  'end_time': 38.9464,
  'low_freq': 23750,
  'high_freq': 28946,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.354,
  'det_prob': 0.51,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 39.9245,
  'end_time': 39.9295,
  'low_freq': 46953,
  'high_freq': 57103,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.504,
  'det_prob': 0.551,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 40.2255,
  'end_time': 40.2456,
  'low_freq': 24609,
  'high_freq': 28081,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.376,
  'det_prob': 0.529,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 40.8365,
  'end_time': 40.841,
  'low_freq': 48671,
  'high_freq': 57813,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.468,
  'det_prob': 0.51,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 40.9515,
  'end_time': 40.9561,
  'low_freq': 46093,
  'high_freq': 62460,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.472,
  'det_prob': 0.543,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 40.9605,
  'end_time': 40.9796,
  'low_freq': 24609,
  'high_freq': 28326,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.429,
  'det_prob': 0.57,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 41.0555,
  'end_time': 41.0614,
  'low_freq': 46093,
  'high_freq': 63209,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.419,
  'det_prob': 0.601,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 41.8345,
  'end_time': 41.8497,
  'low_freq': 23750,
  'high_freq': 30125,
  'class': 'Eptesicus serotinus',
  'class_prob': 0.261,
  'det_prob': 0.514,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 44.7005,
  'end_time': 44.7171,
  'low_freq': 24609,
  'high_freq': 27758,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.441,
  'det_prob': 0.565,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 45.3075,
  'end_time': 45.3148,
  'low_freq': 39218,
  'high_freq': 45000,
  'class': 'Pipistrellus nathusii',
  'class_prob': 0.496,
  'det_prob': 0.527,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 46.6375,
  'end_time': 46.6544,
  'low_freq': 24609,
  'high_freq': 29872,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.331,
  'det_prob': 0.535,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 48.6135,
  'end_time': 48.6313,
  'low_freq': 23750,
  'high_freq': 27929,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.479,
  'det_prob': 0.568,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 49.4555,
  'end_time': 49.472,
  'low_freq': 24609,
  'high_freq': 28447,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.469,
  'det_prob': 0.616,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 49.8765,
  'end_time': 49.8916,
  'low_freq': 22890,
  'high_freq': 28096,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.262,
  'det_prob': 0.542,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 51.0385,
  'end_time': 51.0589,
  'low_freq': 23750,
  'high_freq': 27402,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.435,
  'det_prob': 0.532,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 52.8165,
  'end_time': 52.8352,
  'low_freq': 24609,
  'high_freq': 28308,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.448,
  'det_prob': 0.609,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 63.9615,
  'end_time': 63.9665,
  'low_freq': 48671,
  'high_freq': 57364,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.449,
  'det_prob': 0.521,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 64.0955,
  'end_time': 64.1,
  'low_freq': 47812,
  'high_freq': 62375,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.536,
  'det_prob': 0.592,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 64.2305,
  'end_time': 64.2348,
  'low_freq': 48671,
  'high_freq': 59280,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.502,
  'det_prob': 0.542,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 64.5265,
  'end_time': 64.5309,
  'low_freq': 46953,
  'high_freq': 59250,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.517,
  'det_prob': 0.556,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 64.6335,
  'end_time': 64.6377,
  'low_freq': 46953,
  'high_freq': 62552,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.498,
  'det_prob': 0.565,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 64.7255,
  'end_time': 64.7313,
  'low_freq': 47812,
  'high_freq': 55317,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.576,
  'det_prob': 0.59,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 64.7825,
  'end_time': 64.7864,
  'low_freq': 46093,
  'high_freq': 60372,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.464,
  'det_prob': 0.509,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 64.8295,
  'end_time': 64.8339,
  'low_freq': 47812,
  'high_freq': 58582,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.504,
  'det_prob': 0.52,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 65.0515,
  'end_time': 65.0555,
  'low_freq': 47812,
  'high_freq': 60853,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.518,
  'det_prob': 0.551,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 65.3465,
  'end_time': 65.3521,
  'low_freq': 46953,
  'high_freq': 62630,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.539,
  'det_prob': 0.619,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 65.4035,
  'end_time': 65.4078,
  'low_freq': 46953,
  'high_freq': 64498,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.519,
  'det_prob': 0.583,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 65.4555,
  'end_time': 65.4598,
  'low_freq': 46093,
  'high_freq': 61158,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.472,
  'det_prob': 0.547,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 65.7595,
  'end_time': 65.7639,
  'low_freq': 48671,
  'high_freq': 61572,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.494,
  'det_prob': 0.557,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 82.0955,
  'end_time': 82.103,
  'low_freq': 40078,
  'high_freq': 50492,
  'class': 'Pipistrellus nathusii',
  'class_prob': 0.485,
  'det_prob': 0.558,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 93.2795,
  'end_time': 93.2858,
  'low_freq': 40937,
  'high_freq': 50337,
  'class': 'Pipistrellus nathusii',
  'class_prob': 0.482,
  'det_prob': 0.506,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 93.4895,
  'end_time': 93.4983,
  'low_freq': 39218,
  'high_freq': 48143,
  'class': 'Pipistrellus nathusii',
  'class_prob': 0.476,
  'det_prob': 0.519,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 93.6915,
  'end_time': 93.6991,
  'low_freq': 40078,
  'high_freq': 49124,
  'class': 'Pipistrellus nathusii',
  'class_prob': 0.558,
  'det_prob': 0.586,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 93.8845,
  'end_time': 93.8926,
  'low_freq': 40078,
  'high_freq': 48704,
  'class': 'Pipistrellus nathusii',
  'class_prob': 0.553,
  'det_prob': 0.61,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 93.9795,
  'end_time': 93.9882,
  'low_freq': 40078,
  'high_freq': 50245,
  'class': 'Pipistrellus nathusii',
  'class_prob': 0.546,
  'det_prob': 0.634,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 94.0745,
  'end_time': 94.0818,
  'low_freq': 38359,
  'high_freq': 48093,
  'class': 'Pipistrellus nathusii',
  'class_prob': 0.571,
  'det_prob': 0.61,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 94.1595,
  'end_time': 94.1672,
  'low_freq': 39218,
  'high_freq': 48338,
  'class': 'Pipistrellus nathusii',
  'class_prob': 0.428,
  'det_prob': 0.516,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 94.2455,
  'end_time': 94.2538,
  'low_freq': 39218,
  'high_freq': 49325,
  'class': 'Pipistrellus nathusii',
  'class_prob': 0.484,
  'det_prob': 0.614,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 94.6335,
  'end_time': 94.6411,
  'low_freq': 39218,
  'high_freq': 51013,
  'class': 'Pipistrellus nathusii',
  'class_prob': 0.477,
  'det_prob': 0.575,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 94.9205,
  'end_time': 94.9285,
  'low_freq': 39218,
  'high_freq': 47453,
  'class': 'Pipistrellus nathusii',
  'class_prob': 0.441,
  'det_prob': 0.514,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 95.3725,
  'end_time': 95.377,
  'low_freq': 49531,
  'high_freq': 61128,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.266,
  'det_prob': 0.545,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 96.6615,
  'end_time': 96.6671,
  'low_freq': 45234,
  'high_freq': 72122,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.418,
  'det_prob': 0.558,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 96.7335,
  'end_time': 96.7406,
  'low_freq': 48671,
  'high_freq': 67922,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.456,
  'det_prob': 0.546,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 96.8905,
  'end_time': 96.8966,
  'low_freq': 46093,
  'high_freq': 76002,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.273,
  'det_prob': 0.549,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 96.9455,
  'end_time': 96.9513,
  'low_freq': 46093,
  'high_freq': 77739,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.271,
  'det_prob': 0.51,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 97.0015,
  'end_time': 97.0069,
  'low_freq': 47812,
  'high_freq': 69492,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.507,
  'det_prob': 0.633,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 97.1295,
  'end_time': 97.1349,
  'low_freq': 46953,
  'high_freq': 76717,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.377,
  'det_prob': 0.518,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 97.1815,
  'end_time': 97.1866,
  'low_freq': 46093,
  'high_freq': 70252,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.461,
  'det_prob': 0.541,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 97.2525,
  'end_time': 97.2577,
  'low_freq': 46093,
  'high_freq': 70756,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.406,
  'det_prob': 0.581,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 97.3065,
  'end_time': 97.3113,
  'low_freq': 46093,
  'high_freq': 69663,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.465,
  'det_prob': 0.592,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 97.4345,
  'end_time': 97.4413,
  'low_freq': 46953,
  'high_freq': 68358,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.427,
  'det_prob': 0.622,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 97.5065,
  'end_time': 97.5112,
  'low_freq': 47812,
  'high_freq': 68118,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.501,
  'det_prob': 0.546,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 97.5555,
  'end_time': 97.5604,
  'low_freq': 47812,
  'high_freq': 70738,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.49,
  'det_prob': 0.596,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 97.6125,
  'end_time': 97.6177,
  'low_freq': 46953,
  'high_freq': 68780,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.62,
  'det_prob': 0.701,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 97.8005,
  'end_time': 97.8053,
  'low_freq': 46953,
  'high_freq': 64076,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.464,
  'det_prob': 0.524,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 97.8825,
  'end_time': 97.8888,
  'low_freq': 46953,
  'high_freq': 67549,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.558,
  'det_prob': 0.708,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 97.9645,
  'end_time': 97.9705,
  'low_freq': 46093,
  'high_freq': 60977,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.454,
  'det_prob': 0.589,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 98.1415,
  'end_time': 98.1462,
  'low_freq': 46953,
  'high_freq': 60761,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.522,
  'det_prob': 0.597,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 99.4205,
  'end_time': 99.4258,
  'low_freq': 47812,
  'high_freq': 58314,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.367,
  'det_prob': 0.555,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 122.6685,
  'end_time': 122.6772,
  'low_freq': 46953,
  'high_freq': 58746,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.266,
  'det_prob': 0.589,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 123.5875,
  'end_time': 123.592,
  'low_freq': 46953,
  'high_freq': 60705,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.472,
  'det_prob': 0.532,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 124.0075,
  'end_time': 124.0116,
  'low_freq': 46953,
  'high_freq': 63055,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.416,
  'det_prob': 0.516,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 124.4055,
  'end_time': 124.4113,
  'low_freq': 46953,
  'high_freq': 59920,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.418,
  'det_prob': 0.618,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 124.6235,
  'end_time': 124.6287,
  'low_freq': 47812,
  'high_freq': 60125,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.467,
  'det_prob': 0.571,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 137.5095,
  'end_time': 137.5179,
  'low_freq': 39218,
  'high_freq': 47402,
  'class': 'Pipistrellus nathusii',
  'class_prob': 0.429,
  'det_prob': 0.551,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 138.4235,
  'end_time': 138.4323,
  'low_freq': 39218,
  'high_freq': 46076,
  'class': 'Pipistrellus nathusii',
  'class_prob': 0.534,
  'det_prob': 0.589,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 138.7705,
  'end_time': 138.7794,
  'low_freq': 40078,
  'high_freq': 53222,
  'class': 'Pipistrellus nathusii',
  'class_prob': 0.454,
  'det_prob': 0.559,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 150.4635,
  'end_time': 150.4694,
  'low_freq': 47812,
  'high_freq': 59327,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.396,
  'det_prob': 0.54,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 150.9725,
  'end_time': 150.9793,
  'low_freq': 48671,
  'high_freq': 60727,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.327,
  'det_prob': 0.518,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 154.5045,
  'end_time': 154.517,
  'low_freq': 24609,
  'high_freq': 30158,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.26,
  'det_prob': 0.504,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 155.0555,
  'end_time': 155.0658,
  'low_freq': 27187,
  'high_freq': 33360,
  'class': 'Nyctalus leisleri',
  'class_prob': 0.326,
  'det_prob': 0.526,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 162.1825,
  'end_time': 162.1879,
  'low_freq': 47812,
  'high_freq': 62817,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.505,
  'det_prob': 0.582,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 162.3775,
  'end_time': 162.383,
  'low_freq': 47812,
  'high_freq': 58872,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.517,
  'det_prob': 0.559,
  'individual': '-1',
  'event': 'Echolocation'},
 {'start_time': 162.8625,
  'end_time': 162.8704,
  'low_freq': 47812,
  'high_freq': 61902,
  'class': 'Pipistrellus pipistrellus',
  'class_prob': 0.515,
  'det_prob': 0.682,
  'individual': '-1',

In [20]:
pd.DataFrame(results['pred_dict']['annotation'])

,start_time,end_time,low_freq,high_freq,class,class_prob,det_prob,individual,event
0,3.7705,3.7774,46093,54897,Pipistrellus pipistrellus,0.505,0.541,-1,Echolocation
1,4.3085,4.3139,46093,58971,Pipistrellus pipistrellus,0.512,0.542,-1,Echolocation
2,5.0035,5.0094,45234,60411,Pipistrellus pipistrellus,0.491,0.544,-1,Echolocation
3,5.1515,5.1568,46093,61553,Pipistrellus pipistrellus,0.443,0.519,-1,Echolocation
4,5.2725,5.2776,46093,61355,Pipistrellus pipistrellus,0.557,0.627,-1,Echolocation
...,...,...,...,...,...,...,...,...,...
1571,1787.7745,1787.7848,37500,46349,Pipistrellus nathusii,0.447,0.562,-1,Echolocation
1572,1787.9595,1787.9694,37500,45423,Pipistrellus nathusii,0.517,0.582,-1,Echolocation
1573,1788.2125,1788.2211,39218,47828,Pipistrellus nathusii,0.433,0.557,-1,Echolocation
1574,1788.4146,1788.4226,40078,49782,Pipistrellus nathusii,0.504,0.583,-1,Echolocation
1575,1788.4955,1788.5035,38359,47810,Pipistrellus nathusii,0.378,0.536,-1,Echolocation

In [21]:
pd.DataFrame.from_records(results['pred_dict']['annotation'])

,start_time,end_time,low_freq,high_freq,class,class_prob,det_prob,individual,event
0,3.7705,3.7774,46093,54897,Pipistrellus pipistrellus,0.505,0.541,-1,Echolocation
1,4.3085,4.3139,46093,58971,Pipistrellus pipistrellus,0.512,0.542,-1,Echolocation
2,5.0035,5.0094,45234,60411,Pipistrellus pipistrellus,0.491,0.544,-1,Echolocation
3,5.1515,5.1568,46093,61553,Pipistrellus pipistrellus,0.443,0.519,-1,Echolocation
4,5.2725,5.2776,46093,61355,Pipistrellus pipistrellus,0.557,0.627,-1,Echolocation
...,...,...,...,...,...,...,...,...,...
1571,1787.7745,1787.7848,37500,46349,Pipistrellus nathusii,0.447,0.562,-1,Echolocation
1572,1787.9595,1787.9694,37500,45423,Pipistrellus nathusii,0.517,0.582,-1,Echolocation
1573,1788.2125,1788.2211,39218,47828,Pipistrellus nathusii,0.433,0.557,-1,Echolocation
1574,1788.4146,1788.4226,40078,49782,Pipistrellus nathusii,0.504,0.583,-1,Echolocation
1575,1788.4955,1788.5035,38359,47810,Pipistrellus nathusii,0.378,0.536,-1,Echolocation